@echo off
cd /d C:\xampp\htdocs\blog_project-learning_php
echo 1. Key generate...
C:\xampp\php\php.exe artisan key:generate
echo 2. Database migration...
C:\xampp\php\php.exe artisan migrate
echo 3. Storage link...
C:\xampp\php\php.exe artisan storage:link
echo 4. Cache clear...
C:\xampp\php\php.exe artisan config:cache
echo 5. Server baslatiliyor...
echo Tarayicida: http://localhost:8000
C:\xampp\php\php.exe artisan serve --port=8081
pause